FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    ENV_MODE=deploy

WORKDIR /app

# Upgrade pip
RUN pip install --no-cache-dir --upgrade pip

# Copy only requirements.txt
COPY requirements.txt .
# Install ONLY from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Verify installed versions (optional, but good for Docker build log)
#RUN pip show google-cloud-storage google-auth

COPY docker-entrypoint.sh /app/docker-entrypoint.sh 
RUN chmod +x /app/docker-entrypoint.sh

COPY ./src /app/src

# If your app is in /app/src/main.py and instance is 'app'
ENV PYTHONPATH=/app 
ENTRYPOINT ["/app/docker-entrypoint.sh"]
# Your entrypoint should exec: gunicorn --bind "0.0.0.0:$PORT" "src.main:app"