
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_deploy
    container_name: redline-fitness-games-results
    env_file:
      - ${ENV_FILE:-.env.${ENV_MODE:-deploy}}
    environment:
      - PORT=${PORT:-8080}
      - ENV_MODE=${ENV_MODE:-deploy}
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    restart: always