version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redfullstackflask-web
    ports:
      - "5000:5000"
    environment:
      - ENV_MODE=development
    volumes:
      - ./src:/app/src
      - ./src/static:/app/src/static
    env_file:
      - .env.development
    restart: always

# Build and run
# docker-compose --env-file .env.development up --build

# View logs
#docker-compose --env-file .env.development logs -f

# Stop
#docker-compose down