version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redfullstackflask-web
    env_file:
      - ${ENV_FILE:-.env.development}
    environment:
      - USE_DOCKER=True
      - PORT=${PORT:-5000}
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    volumes:
      - ./src:/app/src
      - ./src/static:/app/src/static
    restart: always